#!/bin/bash
#Used to run .plan files
#To run "run_LifePlanner [file_name.plan]

python translator.py $1 
if [ "$?" = "1" ]; then
    python calendar.py
    rm calendar.py
else 
    echo "Errors thrown from translator."
fi
